swagger: '2.0'
info:
  title: Example yaml.spec
  description:  <iframe srcdoc="&LT;iframe&sol;srcdoc=&amp;lt;img&sol;src=&amp;apos;&amp;apos;onerror=javascript:alert(1)&amp;gt;>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description:  nice
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
