swagger: '2.0'
info:
  title: Example yaml.spec
  description:  <base href="file://"><iframe  src="C:\Windows\iis.log">
paths:
  /accounts:
    get:
      responses:
        '200':
          description:  nice
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
